<a href="https://colab.research.google.com/github/hamza-24-ai/Pytorch_with_practical_deepLearning/blob/main/09_RNN_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset , DataLoader

In [7]:
df = pd.read_csv("/content/100_Unique_QA_Dataset.csv")
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [8]:
# Tokenize

def tokenize(text):
  text = text.lower()
  text = text.replace("?","")
  text = text.replace("'","")
  return text.split()

In [9]:
# Test the tokenizer
tokenize("What is the boiling point of water in Celsius?")

['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius']

In [10]:
# Now generate a vocabulary of tokens
vocab = {'<UNK>' : 0}

In [11]:
def generate_vocab(row):
  tokenize_question = tokenize(row["question"])
  tokenize_answer = tokenize(row["answer"])

  merged_tokens = tokenize_question + tokenize_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [12]:
df.apply(generate_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [13]:
len(vocab)

324

In [14]:
# convert tokens into indices because our machine understand only numbers

def word_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [15]:
word_to_indices("What is the boiling point of water in Celsius?", vocab)

[1, 2, 3, 24, 25, 5, 26, 19, 27]

In [16]:
# create Dataset for our model

class QnA(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    numerical_question = word_to_indices(self.df.iloc[index]["question"],self.vocab)
    numerical_answer = word_to_indices(self.df.iloc[index]["answer"],self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [17]:
dataset = QnA(df,vocab)

In [18]:
# Creating dataLoader

dataLoader = DataLoader(dataset,batch_size=1, shuffle=True)

In [19]:
for question,answer in dataLoader:
  print(question,answer)

tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([[316]])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([[246]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([[307]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[317]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([[321]])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([[162]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([[149]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([[259]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([[155]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([[249]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([[220]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([[285]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[ 10,  11, 157, 158, 159]]) tensor([[160]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([[99]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([[254]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([[154]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([[295]])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([[207]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([[6]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([[131]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([[156]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([[85]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])

In [20]:
import torch.nn as nn

In [24]:
# Building Simple RNN
class MyRNN(nn.Module):

  def __init__(self,vocab_size):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50,64, batch_first=True)
    self.fc = nn.Linear(64,vocab_size)

  def forward(self, question):
    question_embed = self.embedding(question)
    hidden, final = self.rnn(question_embed)
    output = self.fc(final.squeeze(0))

    return output

In [25]:
learning_rate = 0.001
epochs = 100

In [26]:
model = MyRNN(len(vocab))

In [29]:
print(model.parameters())

<generator object Module.parameters at 0x7f6d1d3e57e0>

In [30]:
criterian = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [32]:
for epoch in range(epochs):

  total_loss = 0

  for question,answer in dataLoader:

    optimizer.zero_grad()

    output = model(question)

    loss = criterian(output, answer[0])

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch : {epoch + 1}, loss : {total_loss:.4f}")

Epoch : 1, loss : 528.9056
Epoch : 2, loss : 457.0926
Epoch : 3, loss : 376.4954
Epoch : 4, loss : 317.0027
Epoch : 5, loss : 265.8289
Epoch : 6, loss : 218.0390
Epoch : 7, loss : 173.8242
Epoch : 8, loss : 135.5667
Epoch : 9, loss : 103.2962
Epoch : 10, loss : 78.8183
Epoch : 11, loss : 60.5713
Epoch : 12, loss : 47.2935
Epoch : 13, loss : 37.3188
Epoch : 14, loss : 30.0908
Epoch : 15, loss : 24.6270
Epoch : 16, loss : 20.3740
Epoch : 17, loss : 17.1048
Epoch : 18, loss : 14.4225
Epoch : 19, loss : 12.3729
Epoch : 20, loss : 10.6787
Epoch : 21, loss : 9.3115
Epoch : 22, loss : 8.1769
Epoch : 23, loss : 7.2434
Epoch : 24, loss : 6.4768
Epoch : 25, loss : 5.8106
Epoch : 26, loss : 5.2349
Epoch : 27, loss : 4.7509
Epoch : 28, loss : 4.3112
Epoch : 29, loss : 3.9430
Epoch : 30, loss : 3.6129
Epoch : 31, loss : 3.3186
Epoch : 32, loss : 3.0535
Epoch : 33, loss : 2.8199
Epoch : 34, loss : 2.6182
Epoch : 35, loss : 2.4214
Epoch : 36, loss : 2.2502
Epoch : 37, loss : 2.0945
Epoch : 38, loss : 1.9543
Epoch : 39, loss : 1.8261
Epoch : 40, loss : 1.7073
Epoch : 41, loss : 1.5975
Epoch : 42, loss : 1.4991
Epoch : 43, loss : 1.4041
Epoch : 44, loss : 1.3207
Epoch : 45, loss : 1.2421
Epoch : 46, loss : 1.1671
Epoch : 47, loss : 1.1003
Epoch : 48, loss : 1.0349
Epoch : 49, loss : 0.9791
Epoch : 50, loss : 0.9217
Epoch : 51, loss : 0.8710
Epoch : 52, loss : 0.8229
Epoch : 53, loss : 0.7785
Epoch : 54, loss : 0.7360
Epoch : 55, loss : 0.6972
Epoch : 56, loss : 0.6607
Epoch : 57, loss : 0.6247
Epoch : 58, loss : 0.5931
Epoch : 59, loss : 0.5618
Epoch : 60, loss : 0.5326
Epoch : 61, loss : 0.5057
Epoch : 62, loss : 0.4801
Epoch : 63, loss : 0.4559
Epoch : 64, loss : 0.4330
Epoch : 65, loss : 0.4117
Epoch : 66, loss : 0.3914
Epoch : 67, loss : 0.3715
Epoch : 68, loss : 0.3535
Epoch : 69, loss : 0.3363
Epoch : 70, loss : 0.3201
Epoch : 71, loss : 0.3045
Epoch : 72, loss : 0.2901
Epoch : 73, loss : 0.2759
Epoch : 74, loss : 0.2624
Epoch : 75, loss : 0.2501
Epoch : 76, loss : 0.2383
Epoch : 77, loss : 0.2269
Epoch : 78, loss : 0.2164
Epoch : 79, loss : 0.2061
Epoch : 80, loss : 0.1966
Epoch : 81, loss : 0.1875
Epoch : 82, loss : 0.1787
Epoch : 83, loss : 0.1703
Epoch : 84, loss : 0.1624
Epoch : 85, loss : 0.1551
Epoch : 86, loss : 0.1479
Epoch : 87, loss : 0.1410
Epoch : 88, loss : 0.1346
Epoch : 89, loss : 0.1284
Epoch : 90, loss : 0.1224
Epoch : 91, loss : 0.1171
Epoch : 92, loss : 0.1116
Epoch : 93, loss : 0.1066
Epoch : 94, loss : 0.1016
Epoch : 95, loss : 0.0971
Epoch : 96, loss : 0.0927
Epoch : 97, loss : 0.0886
Epoch : 98, loss : 0.0845
Epoch : 99, loss : 0.0808
Epoch : 100, loss : 0.0771

In [33]:
def predict(model, question, threshold=0.5):

  indexed_question = word_to_indices(question,vocab)

  # tensor
  question_tensor = torch.tensor(indexed_question).unsqueeze(0)

  # get Output

  output = model(question_tensor)

  # convert logits into probability

  prob = torch.nn.functional.softmax(output, dim=1)

  # getting max prob and index no

  probs, index = torch.max(prob, dim=1)

  # checking data
  if probs < threshold:
    print("I don't know what is answer")
  else:
    print(list(vocab.keys())[index])

In [35]:
predict(model, "What is the boiling point of water in Celsius?")

100